### PR TITLE
do not ship docs

### PR DESCRIPTION
**Pull request by OskarStark**
Shall I provide a PR against `master`, too?

### CODE REVIEW

**Comment by Ocramius** [comment]
I'd say that docs should very much live in the distribution...

**Comment by OskarStark** [comment]
Most of the libraries are excluding them and most of the doctrine libraries, too

**Comment by Ocramius** [comment]
I'm thinking of the dozens of times where I wish I had a documentation that was on par with the downloaded library. Considering how little overhead the docs take (compared to tests, for example), I'd rather avoid this change, and even revert it for other Doctrine projects doing this.

**Comment by greg0ire** [comment]
@Ocramius they will end up in production too… I think the archives should be production ready, devs that want docs and tests can use `--prefer-source`. I've already had that debate somewhere else if you are interested: https://github.com/sonata-project/dev-kit/issues/129

**Comment by Ocramius** [comment]
Yes, and I had a similar debate for tests: tests should not be in distribution because they are a lot, and they aren't usable anyway in that state.

Docs are different: docs **are** useful and aren't that many files at all. Exactly like `LICENSE` and `README`, they should stay and provide guidance.

**Comment by greg0ire** [comment]
People that really do not want docs that might have big images in production can have a build step that deletes docs I guess…

**Comment by Ocramius** [comment]
I can only imagine this to be a very marginal problem for docker environments, and then just don't use a language that ships files as main distribution mechanism?

**Comment by greg0ire** [comment]
It's probably OK to ship docs:

```
du -ch doctrine-*/docs Doctrine*/Resources/doc
28K	doctrine-annotations/docs/en
32K	doctrine-annotations/docs
244K	doctrine-dbal/docs/en/reference
256K	doctrine-dbal/docs/en
44K	doctrine-dbal/docs/examples/sharding
48K	doctrine-dbal/docs/examples
12K	doctrine-dbal/docs/design
344K	doctrine-dbal/docs
76K	doctrine-migrations/docs/en/reference
88K	doctrine-migrations/docs/en
92K	doctrine-migrations/docs
112K	doctrine-orm/docs/en/tutorials
120K	doctrine-orm/docs/en/cookbook
536K	doctrine-orm/docs/en/reference
28K	doctrine-orm/docs/en/changelog
808K	doctrine-orm/docs/en
836K	doctrine-orm/docs
20K	doctrine-persistence/docs/en/reference
32K	doctrine-persistence/docs/en
36K	doctrine-persistence/docs
64K	DoctrineBundle/Resources/doc
20K	DoctrineMigrationsBundle/Resources/doc
1.4M	total
```

**Comment by alcaeus** [comment]
Agree with shipping docs - shall we close this, https://github.com/doctrine/common/pull/864 and https://github.com/doctrine/cache/pull/298 and instead make sure docs are not excluded from archives?

**Pull request closed without merging**
